### ISSUE TITLE
can't install 2.1.0

### ISSUE THREAD

**Issue by pyxiscloud** [igorklopov/enclose#102]
hi
i get this bug and can't install 2.1.0:

sudo npm install -g enclose
/usr/bin/enclose -> /usr/lib/node_modules/enclose/bin/enclose.js

> enclose@2.1.0 postinstall /usr/lib/node_modules/enclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.14-linux-x86-7bee6a7 ...
/usr/lib/node_modules/enclose/postinstall.js:165
    throw error;
    ^

Error: 403,https://enclosejs.s3.amazonaws.com/7d197ebe23d70*************70d91a10d/enclose-v0.12.14-linux-x86-7bee6a7.sha256
    at ClientRequest.<anonymous> (/usr/lib/node_modules/enclose/postinstall.js:41:25)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "enclose"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! enclose@2.1.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the enclose@2.1.0 postinstall script 'node postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the enclose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs enclose
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls enclose
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by igorklopov** [comment]
Hi, you seem to cancel automatic payments. So, new enclose version is not shipped for your account. But you may still install old versions, that were released during your expiration period: `npm install enclose@2.0.2`

**Comment by pyxiscloud** [comment]
But i have paid for this month too.
This pay is only for 2.0.2 version?

**Comment by igorklopov** [comment]
You are right. Try again with this issue.
