### ISSUE TITLE
mysql2 - Cannot find module './binlog_dump.js'

### ISSUE THREAD

**Issue by scramble45** [igorklopov/enclose#103]
Using latest 2.1.0 master and the mysql2 module - https://www.npmjs.com/package/mysql2

`undefined:0

Error: Cannot find module './binlog_dump.js'
1) If you want to enclose the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to enclose the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.argv[1].
    at Module._resolveFilename (module.js:325:15)
    at Function.a._resolveFilename (e:0)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at Module.a.require (e:0)
    at require (internal/module.js:12:17)
    at e:0
    at Array.forEach (native)
    at Object.console./thebox/node_code/node_modules/mysql2/lib/packets/index.js.dev (e:0)
    at Module.a._compile (e:0)
`

**Comment by scramble45** [comment]
We have a license and compatibility with latest npm package is Guaranteed. Any idea on how we can make sure this module works?

**Comment by igorklopov** [comment]
Ok. Let me look...

**Comment by scramble45** [comment]
Any luck with this, Igor?

**Comment by PsyTae** [comment]
any updates on this???  I am getting a similar issue with mysql2.


`error  Cannot find module 'es6-promise' from 'c:\NodeCode\Processor\node_modules\mysql2'`

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
