### ISSUE TITLE
return a exit_code !=0 when warnings

### ISSUE THREAD

**Issue by llonchj** [igorklopov/enclose#107]
When building a executable, enclose shows (as far as I'm aware) in the output:
#### information as warning, like:

```
   /repository/tmp/node_modules/geoip2/lib/node_mmdb.node
     warning  Cannot include native addon into executable.
     The addon file must be distributed with executable.
```
#### conditions that might make the executable not working:

```
  /repository/tmp/node_modules/jayson/index.js
    warning  Cannot resolve '__dirname + "/lib"'
    Use a string literal as argument for 'require', or leave it
    as is and specify the resolved file name in 'scripts' option.
```

In the second case, shall enclose process should return a exit_code != 0 to stop automated builds?

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
