### ISSUE TITLE
Issue with winston logging library

### ISSUE THREAD

**Issue by simast** [igorklopov/enclose#11]
Can't get it to work with winston logging library:

Error: ENOENT, no such file or directory

Tried using "dirs" option to include all the required dirs - but still getting the same error. Something is up with "pkginfo" library that winston has a depending on. What could be the problem here?

Please see a sample project:
https://drive.google.com/file/d/0B-ZXYfeVKweHSC1TY2Z6X0x4akE/view?usp=sharing

**Comment by igorklopov** [comment]
In few hours i will release new version, that solves this issue and a number of similar ones. Thanks!

**Comment by igorklopov** [comment]
I fixed `pkginfo` issue in enclose@0.2.6. Please update and try again. And you may post all problems you meet - i will try to fix them ASAP.

**Comment by simast** [comment]
Thanks for the fix, the issue with pkginfo seems to have been solved. But there is another issue with winston logging library where transports are required with non string literals: https://github.com/winstonjs/winston/blob/master/lib/winston/transports.js#L32

How to solve this? Can I use enclose "scripts" param with a glob pattern to include all the node_modules/winston/lib/winston/transports/*.js files?

**Comment by igorklopov** [comment]
You are quite right. I recently made a `dictionary`. It is a set of patches/includes for widely used packages, needed to compile them propery https://github.com/igorklopov/enclose/blob/master/dictionary/winston.js You may look through the dictionary and make some item yourself when you meet a problem. It will be great if you share your patches via a pull request. Anyway, i will help you and make any patch if you are stuck.

**Comment by simast** [comment]
Thanks for the fix. Next time I run into similar issue I will try to get a workaround with dictionaries. Closing this issue.
