### ISSUE TITLE
build a js.map to make exception traceback mode understandable

### ISSUE THREAD

**Issue by llonchj** [igorklopov/enclose#110]
Is there a possibility to obtain a js.map file for the compiled version?

**Comment by aldendaniels** [comment]
Also interested in this

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
