### ISSUE TITLE
Cannot resolve path error

### ISSUE THREAD

**Issue by junaidmalik09** [igorklopov/enclose#111]
I'm trying to make an executable but run into following error:

/usr/local/lib/node_modules/t2-cli/node_modules/usb/usb.js
  warning  Cannot resolve 'binding_path'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.

/usr/local/lib/node_modules/t2-cli/lib/tessel/deployment/javascript.js
  warning  Cannot resolve 'path.join(globRoot, modulePath, "package.json")'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.

I've tried including the file usb.js in the config.js but still the problem persists. My code requires connection over usb and the file usb.js is essential to the operation.

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
