### ISSUE TITLE
arm arch not support

### ISSUE THREAD

**Issue by iamluodong** [igorklopov/enclose#112]
# I test on ubuntu14.04 

main.js

``` javascript
console.log("test");
```

```
enclose -a armv6 main.js
/usr/lib/node_modules/enclose/bin/enclose-v4.4.7-linux-armv6-1bf3b15: 1: /usr/lib/node_modules/enclose/bin/enclose-v4.4.7-linux-armv6-1bf3b15: Syntax error: word unexpected (expecting ")")
```

```
enclose -a armv7 main.js
/usr/lib/node_modules/enclose/bin/enclose-v4.4.7-linux-armv7-c225585: 1: /usr/lib/node_modules/enclose/bin/enclose-v4.4.7-linux-armv7-c225585: Syntax error: word unexpected (expecting ")")
```

I use `enclode main.js` ,Can generate main execute file.

>  npm install -g enclose ,The ARM bin file cant't download(enclose-v4.4.7-linux-armv7-c225585 and enclose-v4.4.7-linux-armv6-1bf3b15) I manually download the two files

**Comment by serkanp** [comment]
you have to compile it with arm7 device..(ex:physical raspberrypi or virtual armv6 os)  
you cannot compile it in ubuntu 14 x86 or x64 pc..

**Comment by iamluodong** [comment]
Yes,you are right. the armxxxx need run on ARM device. 

ARM bin can't run on android device.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
