### ISSUE TITLE
EncloseJS and Express JS

### ISSUE THREAD

**Issue by thiagoanselmo** [igorklopov/enclose#115]
Hello, want to buy the full version, more first like to know if I can add the expression and / public and / views in binary?

When generating the torque it still needs the external files.

app.use (compression ());

app.set ('views', './views'); 
app.set ('view engine', 'Jade');

app.use (bodyParser.json ());
app.use (bodyParser.urlencoded ({extended: true}));

app.use (cookieParser ());
app.use (session ({secret: 'keyboard cat' cookie: {maxAge: 3600000}, resave: true, saveUninitialized: true}))

app.use (express.static ('./public')); <---------------- <------------

 Error: CSS /public not binary

my conf.js

```
module.exports = {
assets: "./public/**/*",
scripts: "./views/**/*"
};
```

Congratulations for the work

**Comment by igorklopov** [comment]
`app.use (express.static ('./public'));` is likely relative to `cwd`. try
`app.use (express.static (__dirname + '/public'));`

**Comment by thiagoanselmo** [comment]
Thank you, work :D with your tip . I am hoping provider to release card to have the paid version , it worth 
Congratulations for the work .
