### ISSUE TITLE
Will not work on a closed network

### ISSUE THREAD

**Issue by mikeyGlitz** [igorklopov/enclose#117]
I tried installing enclosed on a computer that is located on an enclosed network. The installer could not complete because it was attempting to download the enclosed binary from an external network. would there be a way to download the binary, sneakernet it, and add it to $PATH to complete the install?

[enclose.txt](https://github.com/igorklopov/enclose/files/480302/enclose.txt)
[npm-debug.txt](https://github.com/igorklopov/enclose/files/480305/npm-debug.txt)

**Comment by sangthebui** [comment]
I am also having the same issue. @mikeyGlitz, did you ever resolve this?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
