### ISSUE TITLE
Can't contact you

### ISSUE THREAD

**Issue by thiagoanselmo** [igorklopov/enclose#118]
Hello Igor, i wrote you two emails to i..r@klo..v.com w/o any luck. paid via paypal today, but didn't receive any emails w/ license key. Please answer me to thiagoo.anselmoo@gmail.com  Sorry that i'm writing to you here, but i didn't find other way...

Transaction ID: 37R74685NA0515521

**Comment by maca134** [comment]
I have been waiting over 12 hours for this. I'll give it another day, then paypal dispute

**Comment by thiagoanselmo** [comment]
I talked to Igor, he is on the road going home, and therefore failed to generate the licenses will soon be sending us, I'm closing topic.

**Comment by maca134** [comment]
key received

**Comment by thiagoanselmo** [comment]
key received
