### ISSUE TITLE
List evaluation version limitations explicitly 

### ISSUE THREAD

**Issue by mayanklahiri** [igorklopov/enclose#119]
It would be nice to have the docs mention that network access will be cut off after some time in the evaluation version. Happy to subscribe (just did), but silently cutting off network access leads to some serious head scratching and wasted time. I only found out about this limitation by randomly checking [#96](https://github.com/igorklopov/enclose/issues/96)

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
