### ISSUE TITLE
 Call external .exe

### ISSUE THREAD

**Issue by thiagoanselmo** [igorklopov/enclose#120]
Hello in my system I make external calls .exe files by passing parameters. I can can use the encloseJS to add external files in my exe?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
