### ISSUE TITLE
Corrupt executable problem

### ISSUE THREAD

**Issue by leanderlee** [igorklopov/enclose#121]
I have a very complex application we build with enclose. Occasionally, when we run the binary we created from enclose, the output binary returns `Corrupt executable` and quits immediately.

When I debug the problem, seemingly trivial lines of code cause this issue to happen -- could be a one line change that adds in a `return;` statement. With the statement causes the binary to be corrupt, but without the `return;` statement the app compiles and runs properly.

I can't seem to reproduce this in a simpler form, so unfortunately I cannot give you a reproducible test case. I am hoping you might give me a hint as to what might be causing this problem, perhaps a known issue or mis configuration that could cause this?

I am using `enclose@2.2.0` and `node@6.3.1` with `--version 6` and `x64`

**Comment by leanderlee** [comment]
Interestingly, the exact same code compiles fine in `enclose@2.2.0` with `node@4.4.4` and `--version 4`

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
