### ISSUE TITLE
support for node v4.6.0

### ISSUE THREAD

**Issue by kosmasgiannis** [igorklopov/enclose#122]
Hi there,

do you have any plans to support node v4.6.0 anytime soon ? 

Thanks in advance
Giannis

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
