### ISSUE TITLE
is this project active?

### ISSUE THREAD

**Issue by kosmasgiannis** [igorklopov/enclose#125]
If yes, is there any roadmap?

Best

**Comment by igorklopov** [comment]
yes. next version soon

**Comment by kosmasgiannis** [comment]
That's great news, thanks!

**Comment by simast** [comment]
@igorklopov Any update or ETA on the new version? The paid version has "Guaranteed updates to new Node.js versions", yet so far that does not look like the case.

**Comment by igorklopov** [comment]
@simast Please be patient. Node 7 introduced few problems.

**Comment by kosmasgiannis** [comment]
@igorklopov can you please share with us which Node versions do you plan to support in next release? I hope there will be support for the corresponding LTS ones.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
