### ISSUE TITLE
Need help example number 6

### ISSUE THREAD

**Issue by ydubois-fr** [igorklopov/enclose#126]
Hello, I want to test Enclose and especially being able to create an exe with sources inside. 
I can create executables files without the sources inside.
I tested and it works very well
I try to make your example number 6, but unfortunately I have to take me wrong.

I install Enclose with -g on my PC.
"node -p process.arch+process.platform" give "platform x64win32.

I type "node compile.js" and I get an error:
"Assert.js: 85
 throw new assert.AssertionError ((...

Could you help me take your software by hand.
Thank you very much for your help.

sincerely

Yannick

**Comment by igorklopov** [comment]
Hi
Give me full text of assertion error. Also please code that assertion points to.

**Comment by ydubois-fr** [comment]
Hi, thank you for your answer.
This is the error message:

C:\enclose-master\enclose-master\examples\06-http-server-w-assets>node compile.js

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ChildProcess.<anonymous> (C:\enclose-master\enclose-master\bin\enclose.js:209:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

C:\enclose-master\enclose-master\examples\06-http-server-w-assets>

**Comment by ydubois-fr** [comment]
hello, I am interested in buying your software. 
it works very well with a single file but I have a problem for files with assets.
could you tell me how to do ?

Thank you

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
