### ISSUE TITLE
Problem with using rmdir module

### ISSUE THREAD

**Issue by ckyou** [igorklopov/enclose#127]
Hi, 

I'm trying to use [rmdir](https://github.com/dreamerslab/node.rmdir) in my project, but found that always got error when call it.

Here is  a simple example 
```
var rmdir = require('rmdir');

rmdir('/tmp/some-dir', err=>{
    if(err){
        console.log(err)
    }
    console.log('success');
});
```
After compile it (using enclose full version) and run, will get this error
```
undefined:0



TypeError: object is not a function
    at FSReqWrap.oncomplete (e:0)
```

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
