### ISSUE TITLE
can not  download  precompiled binaries

### ISSUE THREAD

**Issue by xihuanhh** [igorklopov/enclose#128]
i  have checked my network is fine, only once i found it has download  about 10%,others all failed,
hope check it.
Thank you.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
