### ISSUE TITLE
Node 7 with --harmony_async_await support?

### ISSUE THREAD

**Issue by JoseExposito** [igorklopov/enclose#129]
Hi,

First at all thank you for this excellent tool.

Do you have plans to add support for Node v7 soon? I need to update to that specified version as it is the only one that supports async/await.

Thank you very much in advance.

**Comment by eliezedeck** [comment]
+1

**Comment by tlghn** [comment]
+1

**Comment by scramble45** [comment]
+1

**Comment by igorklopov** [comment]
Working on this...

**Comment by JoseExposito** [comment]
The latest Node version (7.6.0) ships with v8 5.5 and "--harmony_async_await" is not required any more. Maybe it is worth to support that version?

By the way, the new pipeline with Ignition & TurboFan is now included as well. In theory, the new pipeline looks like: ( https://www.youtube.com/watch?v=r5OWCtuKiAk )

![pipeline](https://cloud.githubusercontent.com/assets/1335948/23301506/8aa33520-fa8a-11e6-964f-9dd2efa70783.png)

@igorklopov with that new architecture the bytecode (and not js code) is "the source of truth".
Do you think this change could potentially used in Enclose to improve the performance?
My understanding is that with this new architecture Enclose code will be as efficient as non compiled code or even more, but you are the expert here, any input on the new stack?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
