### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by Globegitter** [igorklopov/enclose#13]
In most of my projects that are not performance critical I am using [Babel](https://github.com/babel/babel). Just tried out enclose one of these projects but it has issues at least with ES7 syntax, e.g. `module.exports = async function (cmdArgs) {`.

The file that I am building has babel defined as follows:

```
//run.js
require('babel/register')({
  experimental: true,
  loose: true
});

var nodegitFile = require('./nodegit');

nodegitFile(['tests/fixtures/example.txt']);
```

and running `node run.js` works fine.

The error I am getting:

``` js
project/blame-history/nodegit.js
  error  Unexpected token (5:23)
```

which is just after the `async` token.

Any chance to get enclose to support Babel?

**Comment by igorklopov** [comment]
At the moment EncloseJS transforms only .jsx files. I will add Babel transformation in next release (in 2-4 days)

**Comment by Globegitter** [comment]
Awesome yeah that would be really appreciated.

**Comment by igorklopov** [comment]
Please update to enclose 0.2.11 and look at example 08: https://github.com/igorklopov/enclose/blob/master/examples/08-babel/index.es6

**Comment by Globegitter** [comment]
Just tried it out and it does look better, but it does not seem to support 'experimental' mode of babeljs (https://babeljs.io/docs/usage/experimental/)

**Comment by igorklopov** [comment]
Finally i updated to Babel 5 and specified { stage: 0 } to support experimental features.

**Comment by Kurtas** [comment]
Hello, 
Is Babel really supported? I just tried to compile my project which is written in ES7 and it fails on import syntax

```
root@autoboss:/home/autoboss# enclose -v 5.6.0 -x -o tasker /home/autoboss/discovery/src/tasker.js

/home/autoboss/discovery/src/tasker/app.js
  error  Unexpected token import
```

Thanks

**Comment by jakelacey2012** [comment]
I had the same issue, any ideas?
