### ISSUE TITLE
Use tests + runtime information to generate optimized code?

### ISSUE THREAD

**Issue by ben-pr-p** [igorklopov/enclose#130]
Hello,

I was wondering if anyone had investigated the possibility of using an application's test to generate optimized code by compiling function level optimized byte code.

Using something like this to grab the byte code https://github.com/mraleph/irhydra and something like this to ensure optimization https://github.com/NathanaelA/v8-Natives.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
