### ISSUE TITLE
Compile Node.js server application for RHEL6

### ISSUE THREAD

**Issue by AmitRaj07** [igorklopov/enclose#131]
My team has made a server application in **node.js**, which is running on **RHEL6**. We run this application in the development environment through the clear source code file (like main.js etc.) and we are also using the bcrypt module in this application. But my management has decided not to put source code in production, they wanted to put an executable (compiled version of the code) on production, so that an unauthorised person cannot see the code or do some malfunction activity.

**Is it a good way to put executable (compiled version of the code) of a Node.js application or it will be better if we put source code in production?**

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
