### ISSUE TITLE
Subscribed, waiting for the key

### ISSUE THREAD

**Issue by yangqingfeng868** [igorklopov/enclose#132]
@igorklopov 
I subscribed(527078868@qq.com) last night, but have not received any thing about the license or the key thing. I need it for emergency. Would you please send me the key?

**Comment by yangqingfeng868** [comment]
any update? I haven't received any key.

**Comment by ralvs** [comment]
I'm in the same situation. 
I paid 3 days ago and still no key. 
What's going on, Igor ?

**Comment by igorklopov** [comment]
Please check inboxes.

**Comment by ralvs** [comment]
Every thing is fine and working. Tks!!!

**Comment by kolesnikow** [comment]
same here - paid yesterday, but no key :(

**Comment by igorklopov** [comment]
Sorry for delay. Sent both keys!
