### ISSUE TITLE
Support for Node v4.4.7?

### ISSUE THREAD

**Issue by freyr79** [igorklopov/enclose#135]
Hello, 
Is this working on node v.4.x? or only works on v.4.2.x? Our develop environment is node v4.4.7.
We can make a binary but it doesn't work. I wonder encloseJs is only working on the specific node versions.

Thanks,

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
