### ISSUE TITLE
Cannot include native addon into executable.

### ISSUE THREAD

**Issue by scramble45** [igorklopov/enclose#138]
So I converted the node-i2c library to native javascript from coffee script. Which seems to be working: 
[https://github.com/scramble45/i2cjs](https://github.com/scramble45/i2cjs)

I have modified my node-mcp23017 fork to point to this: [https://github.com/scramble45/i2cjs](https://github.com/scramble45/i2cjs), Now I am seeing this when I try to enclose:

````
 $ enclose mcp23017.js

/node_code/node_modules/node-mcp23017/node_modules/i2c/build/Release/i2c.node
  warning  Cannot include native addon into executable.
  The addon file must be distributed with executable.

````

Any suggestions, I am fine with moving the i2c.node to the running folder it doesn't need to be enclosed I just need to code enclosed.

**Comment by igorklopov** [comment]
Then just don't mind that warning. It is just a reminder that you must place `i2c.node` near your main executable when you deploy.

**Comment by scramble45** [comment]
worked... :-)
