### ISSUE TITLE
node-notifier integration

### ISSUE THREAD

**Issue by RubenNL** [igorklopov/enclose#140]
im trying to use the module 'node-notifier'.
it works when i use 'node program.js', but when i have enclosed it, it just dont show the notification.
no errors or stuff.

this is the small file i use:

`const notifier = require('node-notifier');
notifier.notify({
  title: 'My awesome title',
  message: 'This is the message text.',
});`

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
