### ISSUE TITLE
Question - can it be invoked from the client browser ?

### ISSUE THREAD

**Issue by gg4u** [igorklopov/enclose#143]
Can an executable be invoked from client browser?
the use will be for a dynamical data visualisation - so far the code will consume get apis and render data, I would like to license the script.

Can specify usage limits and instruct how to make a test to make a web client interact with the script? thank you.

**Comment by BurakDev** [comment]
No, the result of enclose is a executable binary

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
