### ISSUE TITLE
New version with native module support

### ISSUE THREAD

**Issue by battuashwik** [igorklopov/enclose#144]
@igorklopov , You mentioned about releasing a new version with native module support and dynamic require support by default. Any updates when is the plan for that.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
