### ISSUE TITLE
Compiled executable doesn't work after identical OS reinstall ? 

### ISSUE THREAD

**Issue by ossandust** [igorklopov/enclose#146]
I'm evaluating the enclose compiler on a Raspberry Pi.  Compilation works fine, the executable runs OK. However when I reformat the Flash card with the identical OS image (Raspbian Jessie) and install the executable on it, it doesn't run. ("command not found"). When I redo the complete installation of node.js and all of its modules and dependencies, I can again build a working executable...  I must be doing something wrong - any idea what?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
