### ISSUE TITLE
How to enclose browserified file?

### ISSUE THREAD

**Issue by Koka5** [igorklopov/enclose#149]
I have a file 

https://raw.githubusercontent.com/json-schema-faker/json-schema-faker/master/dist/json-schema-faker.js

and made some custom changes and then using as it is in my nodejs project.

Now when i do enclose this file.. it requires all other files that are already available in the file.
So it is making core require call to those files and it is not found.
and so i get error that "module not found"

` /Users/username/product/app/lib/faker.js
 error  Cannot find module './lorem' from '/Users/username/product/app/lib'
`

Seeking solution to this problem.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
