### ISSUE TITLE
Not loading pages

### ISSUE THREAD

**Issue by TeslaAdis** [igorklopov/enclose#150]
I wanted to try using enclose in my nodeJS projects. Simply by calling enclose app.js , it creates executable , but when i run it , and try to open localhost, it returns This site can’t be reached By reading documentation i dont see anywhere , how do i enclose whole node js project. Am i missing something , and when i enclose it , what is next step on publishing it on webserver?

Sry if it is dumb question

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
