### ISSUE TITLE
command line input

### ISSUE THREAD

**Issue by SamDecrock** [igorklopov/enclose#151]
Hi,

I'm using Node's readline module to ask the user some input:

```js
var readline = require('readline');

var rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout
});

rl.question('Please enter the IP address of xxx: ', function (host) {
	console.log(host);
});
```

However, after compiling, I'm getting:

```
*** Evaluation version. Please subscribe to full version.
Please enter the IP address of xxx: undefined:0



Error: Failed to flush to storage
    at e:0
    at e:0
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

How can I make the app interactive so users can input something?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
