### ISSUE TITLE
Network connections: What does this mean?

### ISSUE THREAD

**Issue by Jonovono** [igorklopov/enclose#153]
Does enclose monitor web requests my app makes? How is it able to limit network connections in the trial version?

Thanks.

**Comment by igorklopov** [comment]
Evaluation version makes binaries with a built-in limitation. The only thing the limitation does is it counts networks packets and eventually blocks them.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
