### ISSUE TITLE
Serial key

### ISSUE THREAD

**Issue by mfonsos** [igorklopov/enclose#154]
Hello igorklopov can you please provide me the key, i made the payment using email : skoupi@gmail.com thank you.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
