### ISSUE TITLE
Support for 6.10.0?

### ISSUE THREAD

**Issue by JasonScopServ** [igorklopov/enclose#155]
Hi would support for node 6.10.0 be hard to add?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
