### ISSUE TITLE
Write to file?

### ISSUE THREAD

**Issue by Jonovono** [igorklopov/enclose#156]
Hi. I am having issues writing to a file. I want to write to files inside of my project. Is this possible? Can I use a database like nedb?

Or what is the recommended way to write to a file to store some data?

thanks.

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
