### ISSUE TITLE
How to use enclose to modify the exe icon 

### ISSUE THREAD

**Issue by hcyhehe** [igorklopov/enclose#157]
I use the enclose to package an exe program , but it don`t have icon , so I want to ask how to modify the exe icon?

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
