### ISSUE TITLE
dirs support

### ISSUE THREAD

**Issue by anhoev** [igorklopov/enclose#158]
Hi, does it support dirs in config file like wiki ? 
I need to use readFileSync but it does not work .

**Comment by igorklopov** [comment]
Dear users of EncloseJS. I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
