### ISSUE TITLE
Typical bugs when using encloseJS

### ISSUE THREAD

**Issue by robinrodricks** [igorklopov/enclose#16]
What are the typical bugs that arise when using encloseJS?
What are required changes in nodejs apps when using encloseJS?

1, Will there be memory leaks?
2. Will there be random crashes/bugs in our applications?
3. Will there be memory corruption occurring?
4. Will events fire properly? 
5. Are you running any unit tests to confirm 100% perfect behaviour compared to vanilla node?
6. I'm using encloseJS to package a binary socket server. How can I test if everything is ok compared to vanilla nodejs?

**Comment by igorklopov** [comment]
EncloseJS is simply a patch for node. It is really 100% node. It is NOT a separate implementation, so no difference whether you run in node environment or in enclosed package. Of course, bugs are possibe. But they are not as deep as you describe. Almost all bugs are "can not compile" or "require module X failed"

**Comment by robinrodricks** [comment]
Thank a lot for your information. Very helpful.
