### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by oebspm** [igorklopov/enclose#19]
Please try to compile this program and then run it.
On MacOS it returns error: "Segmentation fault: 11"
While under node it finishes successfully.

The code: http://pastebin.com/3QLcAdUt

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
