### ISSUE TITLE
Problems with MongoDB, Consolidate

### ISSUE THREAD

**Issue by estvmachine** [igorklopov/enclose#21]
Hello i try to make a executable version of my project Mean.JS (http://meanjs.org/) but i have a problem with the exports of MongoDB and Consolidate, i make a screenshot of this situation.

![image](https://cloud.githubusercontent.com/assets/2062668/7005749/08b64ce8-dc49-11e4-906f-21cc44b3266d.png)

So there are two issues i have to resolve.
1. I have refactorize the require in MongoDB, the Enclose need a explicit path and here its loaded dynamically, but there are many methods...and really its no the only module i have this problem.

[ 'commands/base_command'
, 'admin'
, 'collection'
, 'connection/read_preference'
, 'connection/connection'
, 'connection/server'
, 'connection/mongos'
, 'connection/repl_set/repl_set'
, 'mongo_client'
, 'cursor'
, 'db'
, 'mongo_client'
, 'gridfs/grid'
, 'gridfs/chunk'
, 'gridfs/gridstore'].forEach(function (path) {
var module = require('./' + path);
for (var i in module) {
exports[i] = module[i];
console.log(exports[i]);
}
});
1. And for other side in the exportation of modules in Consolidate give the error "Cannot find module -name module- from path/consolidate/name_module", and when i check the "node-modules" of Consolidate, its empty. I dont know why...

**Comment by igorklopov** [comment]
Ok. I will try to fix

**Comment by estvmachine** [comment]
Thank you very much! :D

**Comment by estvmachine** [comment]
Well the documentation say i have to use 'explicit' dependencies. I  try it, well mongoose have a lot a dynamical dependencies, i dont have a solution for that.

So i not use mongodb, and well consolidate i put explicit the dependencies. And works!, only i need to know how to add binaries dependencies, im ussing node-sqlserver-unofficial and i dont understand how use it external the executable or inside :S.
