### ISSUE TITLE
npm install -g enclose fails on windows

### ISSUE THREAD

**Issue by opensourcegeek** [igorklopov/enclose#27]
I get following error on windows, has anyone had this issue?

> enclose@0.2.25 postinstall C:\Users\User\AppData\Roaming\npm\node_modules\e
> nclose
> node postinstall.js

Downloading precompiled binaries. Please wait ...
Downloading enclose-v0.12.4-win32-41280ee.exe ... 10% 20% 30% 40% 50% 60% 70% 80
% 90%
Downloading mksnapshot-v0.12.4-win32-41280ee.exe ...
C:\Users\Praveen\AppData\Roaming\npm\node_modules\enclose\postinstall.js:131
    throw error;
          ^
Error: getaddrinfo ENOTFOUND enclosejs.s3.amazonaws.com, mksnapshot-v0.12.4-win3
2-41280ee.exe
    at C:\Users\Praveen\AppData\Roaming\npm\node_modules\enclose\postinstall.js:
74:18
    at C:\Users\Praveen\AppData\Roaming\npm\node_modules\enclose\postinstall.js:
67:13
    at process._tickCallback (node.js:355:11)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "-g" "enclose"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! enclose@0.2.25 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enclose@0.2.25 postinstall script 'node postinstall.js'.
npm ERR! This is most likely a problem with the enclose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls enclose
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\User\Praveen\Downloads\stress-test\src\npm-debug.log

**Comment by igorklopov** [comment]
I just installed successfully. Seems that you have a network error. Please try again.
