### ISSUE TITLE
glob, configuration file?

### ISSUE THREAD

**Issue by linus-amg** [igorklopov/enclose#30]
hi, im running into an issue, i would like to add assets to the file, in the readme it says defining the assets as a glob in the configuration file, but i cant find anything about a configuration file, which one is it? how would an example look like?

**Comment by linus-amg** [comment]
i require a .hbs file in my index.js, because i use Handlebars (require('Handlebars') before) but that throws an error running enclose, unexpected token, running it with nodemon, node, forever etc. does work though, any advice?

**Comment by linus-amg** [comment]
``` sh

/Users/lgubenis/projects/sdk-static/node_modules/superstatic/node_modules/jfig/index.js
  warning  Cannot resolve 'require(filename)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/lgubenis/projects/sdk-static/node_modules/superstatic/node_modules/tiny-lr/node_modules/body-parser/lib/types/urlencoded.js
  info  Cannot resolve 'require(name)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/lgubenis/projects/sdk-static/node_modules/superstatic/node_modules/tiny-lr/node_modules/body-parser/index.js
  info  Cannot resolve 'require(loc)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/lgubenis/projects/sdk-static/node_modules/superstatic/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  warning  Cannot include native addon into executable
  The addon package must be distributed with executable
```

**Comment by tony0918** [comment]
Facing same issue here. Just need some extra files for the package. At same time, need to access these files while running command. So any solution here? Thanks.

**Comment by brstdev6** [comment]
Facing the same issue while compiling Kinect2 app. How to "Just list them as a glob in the configuration file" as the docs of 'enclose' specify??

```
`d:\KinectPack\node_modules\kinect2\build\kinect2\v0.1.3\Release\node-v46-win32-x64\kinect2.node
  warning  Cannot include native addon into executable.
  The addon file must be distributed with executable.

d:\KinectPack\node_modules\node-gyp\lib\node-gyp.js
  warning  Cannot resolve '"./" + command'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.

d:\KinectPack\node_modules\node-gyp\lib\node-gyp.js
  warning  Cannot resolve '"./" + c'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.`
```

**Comment by yuriyKazan** [comment]
Looks like I also need an example of the configuration file.
"Error: Directory 'd:\Test\monitoring\test_data' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at Error (native)
    at Object.console.d:\thebox\Test\monitoring\helpers\e_helper.js.exports.getDataToProces (e:0)
    at Object.console.d:\thebox\Test\monitoring\my_test_e.js.dev (e:0)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)"

**Comment by yuriyKazan** [comment]
btw I found answer for my question https://github.com/igorklopov/enclose/wiki/02.Packaging

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
