### ISSUE TITLE
Problems with express

### ISSUE THREAD

**Issue by emmettprexus** [igorklopov/enclose#31]
Hello,

Completely new to node.js and all this, but I seem to have some problems that might not be because of me! :-) I'm getting this error when running: "enclose yoxy.js"

```
d:\yoxy\node_modules\express\lib\view.js
  warning  Cannot resolve 'require(ext.slice(1))'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option
```

Is this something that can be fixed by me, or is it Enclosure that causes the trouble?

I'm using express, request and concat-stream all installed using the "npm install"-command.

// Yoc.

**Comment by emmettprexus** [comment]
Looks like I'm supposed to use a config.js and setup scripts like:

```
module.exports = {
  scripts: "./node_modules/express/lib/**/*"
};
```

But enclose --help gives me an error so It's not of much assistance :)

```
D:\project>enclose --help
  error  Value for 'help' of type 'String' required.
```

How do I get enclose to read the config file? And is my above example correct?

**Comment by igorklopov** [comment]
Please try again with enclose 0.2.29. I seem to solve your issue. If not, please post the error that your application gives (not compilation warnings).
