### ISSUE TITLE
Node Command Line Options

### ISSUE THREAD

**Issue by kjlaw89** [igorklopov/enclose#32]
It would be super convenient to have the capability to compile the application with a list of command line options to run against Node.

I would like to expose garbage collection in my app, which requires me to pass in a command line option to node ("--expose-gc") before global.gc () becomes available.

https://simonmcmanus.wordpress.com/2013/01/03/forcing-garbage-collection-with-node-js-and-v8/

**Comment by kosmasgiannis** [comment]
+1

**Comment by rldcampbell** [comment]
I was also wondering whether it would be possible in the config to supply command line flags such as `"--max_old_space_size=8192"` for the compiled application?  I don't know any other way to set this, `v8.setFlagsFromString()` does not appear to work (with this flag at least) anywhere I have tried. Would this be a simple addition? Many thanks.

**Comment by igorklopov** [comment]
This feature is being developed and will be available soon

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
