### ISSUE TITLE
[Error: ENOENT, lstat '/thebox/Path/ToFolder']

### ISSUE THREAD

**Issue by jmonster** [igorklopov/enclose#34]
Hello there, I can't help but assume I'm doing something dumb here.. but I can't figure it out :)

I have a node project that effectively creates a new folder on the user's machine and copies files into it. Consider this config file:

```
module.exports = {
  scripts: [
    './index.js'
  ],
  assets: [
    './templates/plugin/README.md',
    './templates/project/*.*', './templates/project/bin/*.*', './templates/project/test/*.*',
    './templates/plugin/*.*', './templates/plugin/test/*.*'

  ],
  dirs: [
    './templates/project', './templates/project/bin', './templates/project/test',
    './templates/plugin', './templates/plugin/test'
  ]
};
```

Creating the binary works OK. Running it, to an extent, is also OK -- as in, my CLI options echo out and what not. But when I actually try to call the method that copies the files from the template into a new folder, I get this:

```
[ { [Error: ENOENT, lstat '/thebox/Path/To/Stuff/templates/project']
    errno: -2,
    code: 'ENOENT',
    path: '/thebox/Path/To/Stuff/templates/project' } ]
```

However, I am seeing the following when I run `enclose` which makes me think things are working OK:

```
/Path/To/Stuff/templates/plugin/.DS_Store
  info  The file was included into output executable as raw content
```

Any ideas? :)

**Comment by igorklopov** [comment]
Please try again with enclose 0.2.29. I seem to solve your issue
