### ISSUE TITLE
Not working with gulp

### ISSUE THREAD

**Issue by darky** [igorklopov/enclose#35]
/Users/darky/Desktop/tavmant/node_modules/gulp/bin/gulp.js
  warning  Cannot resolve 'require(env.configPath)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/darky/Desktop/tavmant/node_modules/gulp/bin/gulp.js
  warning  Cannot resolve 'require(env.modulePath)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/darky/Desktop/tavmant/node_modules/gulp/node_modules/liftoff/index.js
  warning  Cannot resolve 'require(resolve.sync(module, {basedir: basedir}))'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/darky/Desktop/tavmant/node_modules/gulp/node_modules/v8flags/index.js
  warning  Cannot resolve 'require(configpath)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/darky/Desktop/tavmant/node_modules/gulp/node_modules/liftoff/lib/silent_require.js
  warning  Cannot resolve 'require(path)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/Users/darky/Desktop/tavmant/node_modules/gulp/node_modules/liftoff/node_modules/rechoir/lib/register.js
  warning  Cannot resolve 'require(modulePath)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

**Comment by igorklopov** [comment]
I made several improvements concerning `v8flags`, `liftoff` and `rechoir`. Please try again with enclose@0.2.30.

**Comment by darky** [comment]
this no show error yet while build, but when call binary do nothing

**Comment by igorklopov** [comment]
Can you post some minimal code that does not work as expected?

**Comment by darky** [comment]
For example, give from [backbone.linear](/darrrk/backbone.linear)
But before, comment 11,14,15,16 lines, bacause also not working karma, gulp-mocha, gulp-istanbul, istanbul-combine

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
