### ISSUE TITLE
Attempt parse required *.coffee as javascript

### ISSUE THREAD

**Issue by darky** [igorklopov/enclose#36]

**Comment by estvmachine** [comment]
This issue suck xd

**Comment by darky** [comment]
coffee hater :)
Problem bigger
Means any what will compiles to js not working

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
