### ISSUE TITLE
compilation warnings with expressjs and ectjs 

### ISSUE THREAD

**Issue by BilalBoulifa** [igorklopov/enclose#39]
I'm getting these warning when trying to compile my project.

 PS D:\Users\bb14193\Downloads\WorkFolder> enclose app.js

d:\Users\bb14193\Downloads\WorkFolder\node_modules\express\lib\view.js
  warning  Cannot resolve 'require(this.ext.substr(1))'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

d:\Users\bb14193\Downloads\WorkFolder\node_modules\ect\node_modules\coffee-
script\bin\coffee
  warning  Cannot resolve 'require(lib + '/coffee-script/command')'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

**Comment by igorklopov** [comment]
coffee-script detected :coffee: https://github.com/igorklopov/enclose/issues/36

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
