### ISSUE TITLE
atom-shell and/or nwjs gui project support

### ISSUE THREAD

**Issue by tracker1** [igorklopov/enclose#4]
It would be really cool if you could add support for either the [atom-shell](https://github.com/atom/atom-shell) and/or [nwjs](https://github.com/nwjs/nw.js) support for gui projects.

**Comment by igorklopov** [comment]
Indeed this will be great. I plan to do something like this. But right now you may try [node-thrust](https://github.com/breach/node-thrust) to create GUI apps. Here is a small example: https://github.com/igorklopov/enclose/tree/master/examples/43-thrust

**Comment by leanderlee** [comment]
I would love to help out on this project. I feel like things will move much faster if you open source it!

**Comment by polarathene** [comment]
+1 Would be great to use this with Electron (formerly atom-shell).

**Comment by etiktin** [comment]
@igorklopov, is this still in the works?
node-thrust seems pretty much dead. Electron is awesome, but currently there's no source code protection solution for it, so this will really be appreciated.

/cc @Penagwin

**Comment by kyuwoo-choi** [comment]
+1 yes

**Comment by chino23** [comment]
@igorklopov if electron will be supported i'll surely buy it. This is the main thing missing there. Please have a look.

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
There is already such an issue opened: https://github.com/zeit/pkg/issues/52

**Comment by ganeshkbhat** [comment]
Alternatively, you an specify an option to open the default browser on start of .exe and run the .exe in quiet/silent mode
