### ISSUE TITLE
Strict mode is ignored (can't use ECMAScript 6 features)

### ISSUE THREAD

**Issue by simast** [igorklopov/enclose#41]
The "use strict" usage seems to be ignored when compiling with enclose. For example, the code below:

``` javascript
"use strict";
let test = true;
```

Is failing with:

> Failure compiling
> Uncaught SyntaxError: Unexpected strict mode reserved word at line 22
> let test = true;
> ^^^^

Here is a sample project:
https://drive.google.com/file/d/0B-ZXYfeVKweHbTh5LVpwWDY0NmM/view?usp=sharing

**Comment by mo4islona** [comment]
+1

**Comment by simast** [comment]
@igorklopov Any update on this issue? I think this is quite a major one, at least for me.. I tried the new enclode and it seems to still ignore "use strict" at least on the global file level (think the issue is that enclose is wrapping our code inside some function with some stuff on top - hence making our "use strict" not the first line inside the wrapped function body).

Waiting for this to be fixed before I invest in the paid version..

**Comment by igorklopov** [comment]
I just tested - this does not work only in 0.12.7 mode. Can you compile your application in `-v 2.5.0`, `-v 4.2.2` or `-v 5.1.0` ?

**Comment by simast** [comment]
My bad, yes - this does seem to work fine in 5.1.0.. Thanks!
