### ISSUE TITLE
thrust_shell error while running in Windows

### ISSUE THREAD

**Issue by ghost** [igorklopov/enclose#42]
Hi,

I installed enclose and node-thrust, and tested the index.js below in Windows 7 SP1. 

``` javascript
var thrust = require('node-thrust');
thrust(function(error, api) {
    var window = api.window({
        root_url: 'https://www.google.com',
        size: {
            width: 1000,
            height: 600
        }
    });
    window.show();
    window.focus();
});
```

It worked if I run "node index.js", but it displayed the following error if I run "index.exe" after compiled it by "enclose index.js".

```
[2015-07-08T03:38:19.148Z] SPAWING d:\thebox\demo\node_modules\node-thrust\vendor\thrust\thrust_shell
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn d:\thebox\demo\node_modules\node-thrust\vendor\thrust\thrust_shell ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

Thanks for any help.

**Comment by Syleron** [comment]
Has anyone found a solution to this problem?

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
