### ISSUE TITLE
not working with log4js-node

### ISSUE THREAD

**Issue by mylady** [igorklopov/enclose#43]
hi,
i use log4js to log some info and whichever log file path i fill in the config file
it always cause a ENOENT error,the result path is append /thebox prefix.
is it a bug or i made some stupid mistake?

**Comment by getmeaway** [comment]
I have a problem with log4js too. 
The exe file crashes when i try to write logs on file. 
If i write logs on console it works fine

**Comment by mylady** [comment]
@getmeaway maybe your problem is something with path, for file out the executale you should use process.cwd()

**Comment by igorklopov** [comment]
No. This is not your problem. The fix will come in next version

**Comment by mylady** [comment]
@getmeaway sorry,i checked process.cwd() when i move the executable to another directory and it remains the same as compile path

**Comment by mylady** [comment]
@igorklopov  THIS IS very weird!
if i run the executable directly in the project folder,it's working and write log to file
if i mkdir dist(in the project folder) and copy the executable and node_modules into that folder,it will report an error that log4js.appender.dateFile module not found
but repeat the same procedure into a folder outside project,it's working again

**Comment by igorklopov** [comment]
Please leave this problem for a while because it is a BUG in enclose. I will fix it very soon. Thx

**Comment by mylady** [comment]
@igorklopov ok
i got a workaround to modified log4js directly require the appenders i use,now it's working fine:)

**Comment by igorklopov** [comment]
:thumbsup: good workaround

**Comment by igorklopov** [comment]
Now fixed in 0.2.30. Please try again. No workaroud needed anymore.

**Comment by mylady** [comment]
it's working great
thx man!
