### ISSUE TITLE
Got an error on centos 6.5

### ISSUE THREAD

**Issue by seonpiao** [igorklopov/enclose#44]
/usr/local/node/lib/node_modules/enclose/bin/enclose-v0.12.5-linux-x64-f2a83c0: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/node/lib/node_modules/enclose/bin/enclose-v0.12.5-linux-x64-f2a83c0)
/usr/local/node/lib/node_modules/enclose/bin/enclose-v0.12.5-linux-x64-f2a83c0: /lib64/libc.so.6: version`GLIBC_2.14' not found (required by /usr/local/node/lib/node_modules/enclose/bin/enclose-v0.12.5-linux-x64-f2a83c0)

**Comment by igorklopov** [comment]
Fixed in 0.2.30. Please try again.
