### ISSUE TITLE
Not working with node-forge

### ISSUE THREAD

**Issue by micksatana** [igorklopov/enclose#46]
I got this error when run enclose with node-forge module inside my script

  info  Cannot resolve 'require(dep)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

I can fix by creating a new file dictionary/node-forge.js as following
<code>module.exports = {
  scripts: [
    "js/*.js"
  ]
};</code>

but the problem is it still shows many warning. so i assume i'm not fixing it correctly.

**Comment by igorklopov** [comment]
`node-forge` seems to be fixed. Please try with latest 1.0.1
