### ISSUE TITLE
Allow require external modules

### ISSUE THREAD

**Issue by darky** [igorklopov/enclose#47]
Many problems there: "Not working with moduleA or moduleB or moduleC, e. t. c."
Introduce support for each of (168533 now modules) seems long time...
Maybe simply allow require module as is from existing node_modules or other external path from file system?
When I try:

```
enclose --nobundle --version 2.3.4 index.js
```

Or even:

```
enclose --nobundle --version 2.3.4 --config config.js index.js
```

Where config.js:

``` javascript
module.exports = {
  dirs: ["./node_modules"]
};
```

Result:

```
node.js:879
    throw new Error('No such native module ' + id);
        ^
Error: No such native module %module_name%
```

**Comment by igorklopov** [comment]
Try replace `require('some-module')` with `require('some-module', 'can-ignore')` in your own code. I know, this is time consuming at first time. But it is backwards compatible (node's `require` does not have second parameter) and you can selectively choose what modules to ignore.

**Comment by igorklopov** [comment]
And dont use `nobundle`. With `nobundle` it is supposed that you pass only one file to compile. This mode is not properly tested and i dont see use cases for it (in your case you dont need it either).

**Comment by darky** [comment]
Thank's. I will try it.

**Comment by darky** [comment]
Yes, `can-ignore` works, but only for single file and not be used ubiquitously, because vendors in node_modules don't know about it. When I used `nobundle`, I hope, that _node_modules_ folder not included in bundle, but inside bundle `require` work properly as is in nodejs project. How I can totally ignore node_modules folder for bundling, but properly require libraries from thence. It's can help with many issues, where need individual approach to each node module.

**Comment by igorklopov** [comment]
Yes, you are right. `can-ignore` is not inherited in node_modules. Leave `can-ignore` and lets take another approach. Place this in your config.js:

```
module.exports = {
  scripts: ["./node_modules/**/*.js"]
};
```

**Comment by darky** [comment]
Building process raise very many warning and errors, seems no good.

**Comment by igorklopov** [comment]
Post some errors here plz.

**Comment by darky** [comment]
/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/map-stream/test/simple-map.asynct.js
  error  Cannot find module 'ubelt' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/map-stream/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/map-stream/test/simple-map.asynct.js
  error  Cannot find module 'stream-spec' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/map-stream/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/pause-stream/test/index.js
  error  Cannot find module 'stream-spec' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/pause-stream/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/pause-stream/test/index.js
  error  Cannot find module 'stream-tester' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/pause-stream/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test/partitioned_unicode.js
  error  Cannot find module 'it-is' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test/split.asynct.js
  error  Cannot find module 'it-is' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test/split.asynct.js
  error  Cannot find module 'ubelt' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test/split.asynct.js
  error  Cannot find module 'stream-spec' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test/try_catch.asynct.js
  error  Cannot find module 'it-is' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/split/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/stream-combiner/test/index.js
  error  Cannot find module 'tape' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/stream-combiner/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test/async.js
  error  Cannot find module 'tape' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test/auto-destroy.js
  error  Cannot find module 'tape' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test/buffering.js
  error  Cannot find module 'tape' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test'

/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test/end.js
  error  Cannot find module 'tape' from '/Users/darky/Desktop/tavmant/node_modules/gulp-connect/node_modules/event-stream/node_modules/through/test'

**Comment by darky** [comment]
It's only 1/9000 of all errors...
All errors same type:
-  Cannot read file or directory, ENOENT
- Cannot find module

**Comment by igorklopov** [comment]
Lets return to `can-ignore` :) Place `can-ignore` to all `require`s and remove (or rename) `node_modules` folder so that enclose will not follow the require links. Then try to enclose your project.

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
