### ISSUE TITLE
gulp-connect not working

### ISSUE THREAD

**Issue by darky** [igorklopov/enclose#48]
Error: ENOENT: no such file or directory, open '/thebox/Users/.../node_modules/gulp-connect/node_modules/connect/node_modules/type-is/node_modules/mime/types/mime.types'

Seems it relative to [connect in dictionary](/igorklopov/enclose/blob/master/dictionary/connect.js)

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
