### ISSUE TITLE
Error with Mincer library

### ISSUE THREAD

**Issue by dapriett** [igorklopov/enclose#52]
Hello,

I wanted to try out enclose on my sails app, but I'm running into errors with a module I'm using, [mincer](https://github.com/nodeca/mincer):

```
/sails-app/node_modules/mincer/lib/mincer/engines/handlebars_engine.js
  error  Cannot find module 'handlebars' from '/sails-app/node_modules/mincer/lib/mincer/engines'

/sails-app/node_modules/mincer/lib/mincer/engines/jade_engine.js
  error  Cannot find module 'jade' from '/sails-app/node_modules/mincer/lib/mincer/engines'

/sails-app/node_modules/mincer/lib/mincer/engines/stylus_engine.js
  error  Cannot find module 'stylus' from '/sails-app/node_modules/mincer/lib/mincer/engines'

/sails-app/node_modules/mincer/lib/mincer/processors/autoprefixer.js
  error  Cannot find module 'autoprefixer-core' from '/sails-app/node_modules/mincer/lib/mincer/processors'

/sails-app/node_modules/mincer/lib/mincer/compressors/csso_compressor.js
  error  Cannot find module 'csso' from '/sails-app/node_modules/mincer/lib/mincer/compressors'
```

I'm using the example sails app compile script: https://github.com/igorklopov/enclose/blob/master/examples/26-sails/compile.js

How would I modify it to ignore those requires in that module?

Thanks!

**Comment by dapriett** [comment]
In the config is there a way to patch node_modules?

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
