### ISSUE TITLE
error when executable invoked without extension

### ISSUE THREAD

**Issue by ainglese** [igorklopov/enclose#57]
i've made a couple of test and with a really simple test.js:

```
console.log('all of your bases are belong to us');
```

and invoking: `enclose test.js -o testbin.exe`

when executable is invoked from command line:

```
test_enclose>testbin

test_enclose>testbin.exe
all of your bases are belong to us

test_enclose>
```

it seems that when executed without extension enclose is not working as expected

addendum: windows platform of course

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
