### ISSUE TITLE
Node 4

### ISSUE THREAD

**Issue by addelajnen** [igorklopov/enclose#59]
I would really appreciate support for latest (4.0) nodejs native modules.

**Comment by serkanp** [comment]
me too :)

**Comment by simast** [comment]
+1 Waiting.. This project has been going very slow lately.. hopefully its not dead and node 4.x support is coming soon.

**Comment by igorklopov** [comment]
I work on 4.x now. Please be patient :)

**Comment by simast** [comment]
Good news! Thanks @igorklopov

**Comment by addelajnen** [comment]
Very good news, thanks!

**Comment by estvmachine** [comment]
Woh amazing

**Comment by bymaximus** [comment]
Not possible let us help you?

**Comment by igorklopov** [comment]
Nodejs 4 is very very soon. Totally 0.12.7, 2.5.0 and 4.x will be supported.

**Comment by addelajnen** [comment]
Great igor!

**Comment by nataliethistime** [comment]
:+1: Hoping this is still coming along!

**Comment by igorklopov** [comment]
Node.js 4.2.2 and 5.0.0 are available in current EncloseJS. Please try again.

**Comment by estvmachine** [comment]
Awesome thanks!
