### ISSUE TITLE
Could you help me to use this for loopback framework?

### ISSUE THREAD

**Issue by speed1speed1** [igorklopov/enclose#60]
I've tried compiler loopback, but error.
fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/thebox/Users/me/node/loopback-example-angular/node_modules/loopback/server/middleware'

What happened?
Thank you.

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
