### ISSUE TITLE
Executable not signable.

### ISSUE THREAD

**Issue by julian-weinert** [igorklopov/enclose#62]
The resulting executable cannot be code signed using Apples `codesign`.
It constantly fails without saying anything but the executable failed validation:

```
$ /usr/bin/codesign --force --sign - externalExecutable
    nodeApp: main executable failed strict validation
```

Another try was signing not strict. This time one more hint came out:

```
$ /usr/bin/codesign --verbose=4 --no-strict --force --sign - nodeApp 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: the __LINKEDIT segment does not cover the end of the file (can't be processed) in: nodeApp
```

**Comment by igorklopov** [comment]
Thanks for bugreport. Indeed, it does not work. I will fix it in a week (hopefully).

**Comment by julian-weinert** [comment]
Sure, you're welcome. More important: thanks for this awesome project!
Also I was not able to build it as 64bit, is there an option for that?

**Comment by igorklopov** [comment]
What error you get when you can't build as 64 bit?

**Comment by BurakDev** [comment]
@julian-weinert the option is --x64

**Comment by KimSchneider** [comment]
Hi, I'd like to know what the status of this bug is.

We are really interested in releasing some stuff using enclose, but without signing it is a showstopper.

**Comment by igorklopov** [comment]
Please try with enclose@2.2.0. Seems to be fixed.
