### ISSUE TITLE
Error: yield can't run at enclose-v0.12.7

### ISSUE THREAD

**Issue by Srar** [igorklopov/enclose#68]
Code:
![6f996143-2019-49d3-b2b3-62bc1a61a930](https://cloud.githubusercontent.com/assets/12068066/11269303/25644074-8ef1-11e5-8665-25ec39dcaf85.png)

Error message:
![f0bcd74c-5f56-4e8f-ad3b-c31afaf1e606](https://cloud.githubusercontent.com/assets/12068066/11269315/37b1ff64-8ef1-11e5-9e81-543789748561.png)

**Comment by AleCaste** [comment]
I am having the same problem with node version 0.12.10

```
  error  evalmachine.<anonymous>:61
  co(function*(){
             ^
Unexpected token *
```

Those node versions require the --harmony-generators flag in order to work with generators.
But how can we specify this in Enclose?

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
