### ISSUE TITLE
require and socket.io bug

### ISSUE THREAD

**Issue by ghost** [igorklopov/enclose#69]
run  compile big source Failed to read code 
example:

'use strict';
var nodemailer = require('nodemailer');
var jade = require('jade');
var request = require('request');
var fs = require('fs');
var session = require('express-session');
var cookieParser = require('cookie-parser');
var express = require('express');
var app = express();
var http = require('http').createServer(app).listen(80);
var io = require('socket.io').listen(http);
io.set('origins',  'localhost:*');
io.on('connection', (socket)=> {
    socket.on('listen_1', (data)=> {});
    socket.on('listen_2', (data)=> {});
    socket.on('listen_3', (data)=> {});
    socket.on('listen_4', (data)=> {});
    socket.on('listen_5', (data)=> {});
    socket.on('listen_6', (data)=> {});
    socket.on('listen_7', (data)=> {});
    socket.on('listen_8', (data)=> {});
    socket.on('listen_9', (data)=> {});
    socket.on('listen_10', (data)=> {});
    socket.on('listen_11', (data)=> {});
    socket.on('listen_12', (data)=> {});
    socket.on('listen_13', (data)=> {});
    socket.on('listen_14', (data)=> {});
    socket.on('listen_15', (data)=> {});
    socket.on('listen_16', (data)=> {});
    socket.on('listen_17', (data)=> {});
    socket.on('listen_18', (data)=> {});
    socket.on('listen_19', (data)=> {});
    socket.on('listen_20', (data)=> {});
    socket.on('listen_21', (data)=> {});
    socket.on('listen_22', (data)=> {});
    socket.on('listen_23', (data)=> {});
    socket.on('listen_24', (data)=> {});
    socket.on('listen_25', (data)=> {});
    socket.on('listen_26', (data)=> {});
    socket.on('listen_27', (data)=> {});
    socket.on('listen_28', (data)=> {});
    socket.on('listen_29', (data)=> {});
    socket.on('listen_30', (data)=> {});
    socket.on('listen_31', (data)=> {});
    socket.on('listen_32', (data)=> {});
    socket.on('listen_33', (data)=> {});
    socket.on('listen_34', (data)=> {});
    socket.on('listen_35', (data)=> {});
    socket.on('listen_36', (data)=> {});
    socket.on('listen_37', (data)=> {});
    socket.on('listen_38', (data)=> {});
    socket.on('listen_39', (data)=> {});
    socket.on('listen_40', (data)=> {});
    socket.on('listen_41', (data)=> {});
    socket.on('listen_42', (data)=> {});
    socket.on('listen_43', (data)=> {});
    socket.on('listen_44', (data)=> {});
    socket.on('listen_45', (data)=> {});
    socket.on('listen_46', (data)=> {});
});
console.log('OK');

Result 
## RUN Failed to read code 

Help pless

**Comment by igorklopov** [comment]
I confirm. Working on it now...

**Comment by igorklopov** [comment]
By the way only 5.1.0 compilation is affected. You may temporarily switch to 4.2.2

**Comment by ghost** [comment]
-v 4.2.2 also simply need more code 

if require('jade')

**Comment by ghost** [comment]
var nodemailer = require('nodemailer');
var jade = require('jade');
var request = require('request');

a conflict module jade

**Comment by ghost** [comment]
It may extend the time to enclose the assembly and does not have time

**Comment by onsamp** [comment]
Debian 

build   OK
run      OK

**Comment by igorklopov** [comment]
Numerous arrow functions problem was fixed long ago. Closing.
