### ISSUE TITLE
Windows XP?

### ISSUE THREAD

**Issue by skevy** [igorklopov/enclose#70]
I know this sounds crazy, but I need to use enclose.js to build an app for Windows XP.

It seems that Visual Studio 2013 doesn't support building for Windows XP unless you set a certain flag.

Does anyone on your team have experience with this?

Thanks,
-Adam

**Comment by igorklopov** [comment]
What error message do you have on XP? I thought it works on XP but it is untested.

**Comment by igorklopov** [comment]
![enclose-winxp](https://cloud.githubusercontent.com/assets/1372431/12080937/42adeeb0-b27c-11e5-8ccf-b484841c487f.png)
Seems to work fine.
