### ISSUE TITLE
run the executable in different folder

### ISSUE THREAD

**Issue by guillermojmc** [igorklopov/enclose#71]
Hi! I have a similar problem like this [#43](https://github.com/igorklopov/enclose/issues/43)
I'm trying to compile my project based on [angular-fullstack 2.1.0](https://github.com/DaftMonk/generator-angular-fullstack/tree/2.1.0). After running `grunt build`, in the dist  folder run `enclose -v 0.12.7 --x64 -c server/compile-config.js server/app.js`, then run `NODE_ENV=production ./server/app` and it works well.

If I move the folder to another with the _same distance_, it works great too:
![captura de pantalla 2015-12-03 a las 4 19 23](https://cloud.githubusercontent.com/assets/2019591/11554259/30ade6e0-9975-11e5-855a-68f656efca23.png)

This is my config file

```
// server/compile-config.js
module.exports = {
  scripts: './**/*.js',
  assets: '../client/**/*'
};
```

I have excluded most of the dependencies with 'cant-encode'

But if I move the project to a folder above or below shows this error:
![captura de pantalla 2015-12-03 a las 4 09 13](https://cloud.githubusercontent.com/assets/2019591/11554084/ae17562c-9973-11e5-8e75-30e5f76e8ba9.png)

**Comment by igorklopov** [comment]
I fixed the bug. Now enclose@1.0.4 is building. It will have the bugfix when released. Thanks.

**Comment by igorklopov** [comment]
Please try again with 1.0.4.
