### ISSUE TITLE
Build fails with error but exit code is 0

### ISSUE THREAD

**Issue by julian-weinert** [igorklopov/enclose#72]
I encounter an `Unexpected token` build error but enclosure still exits with a 0 status code.
This makes my IDE try to build other dependencies and the error message to be lost in void.

**Comment by igorklopov** [comment]
I will check and fix. Thanks

**Comment by igorklopov** [comment]
I could not reproduce the bug. In all my bad cases (even `Unexpected token`) i get 1 as status code. Can you give me more info about what you did to get the issue?

**Comment by julian-weinert** [comment]
@igorklopov sorry, I totally about forgot this... The most basic example would be calling enclose with an unrecognised argument:

```
enclose --unknown-argument && echo "exit code $?"

  error  Invalid option '--unknow-argument' - perhaps you meant '--no-color'?

exit code 0
```
