### ISSUE TITLE
Desperately in need of a "Getting Started" guide.

### ISSUE THREAD

**Issue by nevf** [igorklopov/enclose#75]
enclose looks extremely interesting and from what I can see is better than competing solution such as nexe & jx core.

However there is a serious lack of information on how to use enclose. Sure there are plenty of examples, but no documentation on how to compile the examples. If you want people to quickly get up and running with enclose please provide better documentation. Saying type `enclose` to see the command line options doesn't cut it.

Some of the examples include a compile.js file, but there are no doc's on what this is about. I think you use `node compile.js` and it runs enclose but when I do this for the `06-http-server-w-assets` example I get.

```
C:\webapps\play\enclose\examples\06-http-server-w-assets>node compile.js

C:\webapps\play\enclose\bin\enclose.js:117
      if (error) throw error;
                       ^
Error: Compiler not found for v4.2.3-win64
    at ChildProcess.<anonymous> (C:\webapps\play\enclose\bin\enclose.js:178:12)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:787:12)
```

enclose was installed with the -g option and I can compile simple apps. Now what?

**Comment by igorklopov** [comment]
You are right. I will first finish command line interface description (full for `enclose`) and then make a Getting Started guide. But first of all i shoud fix the bugs. Because what you get "Compiler not found for v4.2.3-win64" seems just a bug. How did you get it? Did you just install enclose.js and run compile.js from example 06? Did you do something more than that? Please give `node -p process.arch+process.platform`

**Comment by nevf** [comment]
@igorklopov `node -p process.arch+process.platform` gives `x64win32`

If I run `node compile.js` I get the error shown previously.

If I run `enclose -x compile.js -o index.exe` there are no errors. Then when I run `index.exe` I get:

```
>index
*** Evaluation version. Please subscribe to full version.
undefined:0



Error: File 'binaries.json' not found. Reinstall EncloseJS
    at exec (e:0)
    at Object.console.+c+:+\+t+h+e+b+o+x+\+w+e+b+a+p+p+s+\+p+l+a+y+\+e+n+c+l+o+s+e+\+e+x+a+m+p+l+e+s+\+0+6+-+h+t+t+p+-+s+e+r+v+e+r+-+w+-+a+s+s+e+t+s+\+c+o+m+p+i+l+e+.+j+s.dev (e:0)
    at r (e:0)
    at console.+c+:+\+t+h+e+b+o+x+\+w+e+b+a+p+p+s+\+p+l+a+y+\+e+n+c+l+o+s+e+\+e+x+a+m+p+l+e+s+\+0+6+-+h+t+t+p+-+s+e+r+v+e+r+-+w+-+a+s+s+e+t+s+\+c+o+m+p+i+l+e+.+j+s.flags (e:0)
    at e:0
    at _third_party_main.js:4:8
    at NativeModule.compile (node.js:954:5)
    at Function.NativeModule.require (node.js:902:18)
    at node.js:59:22
    at doNTCallback0 (node.js:419:9)
```

**Comment by igorklopov** [comment]
You run `enclose -x compile.js -o index.exe` and you should run `enclose -x index.js -o index.exe`. Because `index.js` is the application to compile. And `compile.js` is a script that compiles using enclose.
