### ISSUE TITLE
[Error] Outdated version of EncloseJS. Please update

### ISSUE THREAD

**Issue by calebboyd** [igorklopov/enclose#76]
`Code 0x619c67a8. Outdated version of EncloseJS. Please update`

Running the latest version (1.0.5) of enclose on Windows 10, Node 4.2.4, targeting 4.2.4

**Comment by calebboyd** [comment]
It seems to have something to do with my babel6 configuration.

**Comment by dotenorio** [comment]
+1

**Comment by igorklopov** [comment]
Please reinstall enclosejs to 1.0.6 that was just released. And retry.

**Comment by dotenorio** [comment]
Worked for me, thanks! :tada:

**Comment by calebboyd** [comment]
Build worked this time. Now I just have `Failed to read code` message when executing.

**Comment by igorklopov** [comment]
http://enclosejs.com/faq

**Comment by calebboyd** [comment]
Not sure what you wanted to share in the faq. Removing the `--x64` flag seemed to solve the issue though. (on an x64 machine)

**Comment by igorklopov** [comment]
I wanted to say that `--features=no` may also solve the issue and your binary stays x64. Btw, did you get `CPU lacks feature` message? Or just `Failed to read code`?

**Comment by calebboyd** [comment]
Building without x64 is an acceptable solution. Thanks for your responsiveness.

**Comment by calebboyd** [comment]
I was only getting the `Failed to read code` message.

**Comment by gabemarshall** [comment]
I'm getting "error  Code 0x619226b0. Outdated version of EncloseJS. Please update".. 
Windows 7, enclose 1.3.1, nodejs 4.4.1.

Any suggestions?
