### ISSUE TITLE
Cant pay for tool

### ISSUE THREAD

**Issue by maca134** [igorklopov/enclose#77]
Not sure whats going on but the paypal sub doesnt work. Errors out @ paypal. Called paypal to check for problems on my side, they said it all looks fine.

I'd love to get the tool, please take my money =D

**Comment by igorklopov** [comment]
Hello, Matthew.
I kindly ask you to help me with this problem. Because there may be other people that can not pay too.
Please post some screenshots so that i can talk to paypal too.
If you need the license asap, please email me directly igor(at)klopov(dot)com.

**Comment by igorklopov** [comment]
Maybe bven better sending screenshots to me because it can disclose your financial information.
