### ISSUE TITLE
confusing message in the error

### ISSUE THREAD

**Issue by teraPacket** [igorklopov/enclose#80]
I am running ubuntu 14.04 with kernel 3.19.0-33-generic.  When running the latest enclose, got the following error.  I don't know what action I should take on sentence "Run with or without --x64 flag".
Any ideas?  Thanks.

```
$ enclose

/usr/local/lib/node_modules/enclose/bin/enclose.js:125
      if (error) throw error;
                       ^
Error: Your OS does not support v4.2.4-linux-x64. Run with or without --x64 flag.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/enclose/bin/enclose.js:180:10)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:795:12)

```

**Comment by igorklopov** [comment]
Did you run just `enclose` command to get this?

**Comment by teraPacket** [comment]
my command line is 

```
$ enclose test.js
```

test.js is a simple js file

```
console.log("Hello");
```

**Comment by jitendra-khatri** [comment]
I am facing the same issue. @capstar Have you got any solution for this?

**Comment by teraPacket** [comment]
Unfortunately no.

**Comment by igorklopov** [comment]
Probably you specified bad nodejs version to wrap your project in. For example you specified 4.2.4, but enclosejs can wrap only in 4.2.6. Please review your compilation command line.

**Comment by igorklopov** [comment]
Another way refer to `node_modules/enclose/bin` directory and try to run desired compiler manually. Also you may list that directory here so that i can investigate further.

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
