### ISSUE TITLE
Raspberry Pi Zero - Running enclose results in silent failure

### ISSUE THREAD

**Issue by msolters** [igorklopov/enclose#84]
I am running node 4.3.0 on a raspberry pi zero.  This node version is for armv6.

When I run `enclose` on a given .js file, it does not throw any errors, but it does not create any files either!  It just fails silently.  The same .js file compiles fine on my 64 bit desktop running Ubuntu.

**Comment by igorklopov** [comment]
It is a silent segfault (you can run in gdb to see it). Armv6 is not yet supported by enclosejs. It will be supported soon.

**Comment by igorklopov** [comment]
Unfortunately, enclose 2.0.0 still does not support ARMv6. I plan to start supporting in 2.1.0. Lets wait little more.

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
