### ISSUE TITLE
RedHat x86: cannot execute binary file

### ISSUE THREAD

**Issue by brynzzza** [igorklopov/enclose#85]
I'am trying to run a binary I've crated on a Mac on another machine, this machine runs RedHat x86-64, this is what UNAME command say
`Linux spc08ib 2.6.32-279.el6.x86_64`

Enclose is installed by NPM on the Mac. I try different combinations of `enclose` command and `enclose/bin/enclose-v4.3.0-darwin-x86-0f2810a`, -x and -f flags, but when I trying to run binary file there is `cannot execute binary file` error appears. 

Do you have any ideas why this can happens? Is it RedHat issue?

**Comment by igorklopov** [comment]
Can you run `./enclose-v4.3.0-darwin-x86-0f2810a` directly? Does `chmod +x enclose-v4.3.0-darwin-x86-0f2810a` fixes it?

**Comment by igorklopov** [comment]
Sorry, i misunderstood you. EncloseJS does not currently support crosscompilation. You should compile on Mac to make binaries that will run on Mac. You should compile on RedHat to make binaries that will run on RedHat (other Linuxes are also fine).

**Comment by brynzzza** [comment]
Igor, thanks for your response 

Compiling my script on virtual CentOS helps me make binary file that runs correctly on RedHat server as well.
