### ISSUE TITLE
[Error] Outdated version of EncloseJS. Please update - Enclose 1.3.1

### ISSUE THREAD

**Issue by gabemarshall** [igorklopov/enclose#86]
I'm getting "error  Code 0x619226b0. Outdated version of EncloseJS. Please update".. 
Windows 7, enclose 1.3.1, nodejs v5.9.1

I've tried reinstalling Enclose, reinstalling nodejs, etc.. no luck. Any suggestions?

**Comment by igorklopov** [comment]
Hi, Gabe. In few days i will release version 2.0.0. This bug will be fixed there. Thanks!

**Comment by gabemarshall** [comment]
Much appreciated, thanks!

**Comment by igorklopov** [comment]
Enclose 2.0.0 is just released. Please try again with 2.0.0 and give feedback.

**Comment by gabemarshall** [comment]
Works great now, thank you!
