### ISSUE TITLE
cpu lacks error 

### ISSUE THREAD

**Issue by ta3pks** [igorklopov/enclose#87]
![screenshot from 2016-03-27 00-49-44](http://i.imgur.com/16B7ybT.png)

**Comment by igorklopov** [comment]
http://enclosejs.com/faq

**Comment by gabemarshall** [comment]
When I first started using enclosejs I ran into this frustration as well (until I read the FAQ). Why not have the --features=no as a default? Maybe there's a valid reason for having it the other way, but just figured I'd offer my input.

**Comment by igorklopov** [comment]
@gabemarshall Great idea, Gabe. 'features' option is removed from 2.0.0. 'features=no' is the only option at this moment.
