### ISSUE TITLE
EncloseJS compilation Error in RedHat Linux64

### ISSUE THREAD

**Issue by maathavant** [igorklopov/enclose#88]
![linux-error](https://cloud.githubusercontent.com/assets/14833023/14246557/ac1f81c8-fa85-11e5-9839-5b3c20950ec9.jpg)

We are trying to use EncloseJS in our product for obfuscation. We are getting the above error in Linux system.Please provide us a solution as soon as possible. If it works then will go for licensed version.thanks

**Comment by igorklopov** [comment]
Please post your OS version. The more info i have, the less time i spend on reproduction. Thanks!

**Comment by igorklopov** [comment]
Does Digital Ocean have your RedHat distribution as an image?

**Comment by maathavant** [comment]
Red Hat Enterprise Linux Server release 6.5 (Santiago)

**Comment by igorklopov** [comment]
Enclose 2.0.0 is just released. It is tested in CentOS 6.7. I hope it will work in your environment. Please try again with 2.0.0 and give feedback.
