### ISSUE TITLE
code protection

### ISSUE THREAD

**Issue by hashseed** [igorklopov/enclose#9]
If you are using V8's serializer/deserializer to implement enclose.js, then the source code is not really protected. It has to be included, and as such, can be read out if you know where to look.

**Comment by igorklopov** [comment]
The source code does not have to be included in snapshot. EncloseJS uses similar approach as nw.js. The source code is absent in both EncloseJS and nw.js

**Comment by hashseed** [comment]
The optimizing compiler requires source code. Does EncloseJS disable it?

**Comment by igorklopov** [comment]
Unfortunately i cannot disclose the internals of EncloseJS while it is a closed source project. Please refer to nw.js sources - you will find interesting information there.
