### ISSUE TITLE
invalid string length error 

### ISSUE THREAD

**Issue by ta3pks** [igorklopov/enclose#90]
https://gist.github.com/NikosEfthias/4db632d0bfb10690376f66781d86d7ec

**Comment by igorklopov** [comment]
Enclose 2.0.0 is just released. It addresses this issue. Please try again with 2.0.0 and give feedback.

**Comment by NikosEfthias** [comment]
@igorklopov  after updating to v2.0.0 my license invalidated

**Comment by ta3pks** [comment]
just now installed wasiting to try

**Comment by igorklopov** [comment]
Duplicate of https://github.com/igorklopov/enclose/issues/89. Closing
