### ISSUE TITLE
What NodeJS version is bundled inside the package?

### ISSUE THREAD

**Issue by jviotti** [igorklopov/enclose#93]
Hey there,

Thanks for such amazing project. We're eager to make use of it to distribute a CLI version of http://www.etcher.io.

What NodeJS version is bundled inside the package? The main concern being that we use some ES6 new features from recent NodeJS versions. v4.0 should be more than enough for us.

**Comment by igorklopov** [comment]
Hi, Juan!
https://github.com/igorklopov/enclose/blob/master/bin/binaries.json
This is the list of supported OSes and runtime versions (i call nodejs "runtime" of a packaged application). Right now 0.12.13, 4.4.2 and 5.10.0 are supported.

**Comment by jviotti** [comment]
Awesome, thanks a lot. I'll close this issue and be looking forward to run the trial with our app.
