### ISSUE TITLE
ETA on Node.js 6.x version?

### ISSUE THREAD

**Issue by simast** [igorklopov/enclose#94]
The node 6.x has a new V8 version with some significant new ES6/7 language features. Just curious if there is any ETA on when we can expect enclose to support 6.x?

**Comment by igorklopov** [comment]
HI, Simas. In a week or less!

**Comment by simast** [comment]
@igorklopov Any updates on Node 6.x version?

**Comment by nroe** [comment]
any news?

**Comment by igorklopov** [comment]
Almost ready...

**Comment by igorklopov** [comment]
Enclose 2.1.0 is out. Please try.
