### ISSUE TITLE
Template Strings

### ISSUE THREAD

**Issue by ericrange** [igorklopov/enclose#99]
Hey what about template strings in "require"?
Right now, i get following error message:

```
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option.
```

**Comment by igorklopov** [comment]
Dear users of EncloseJS! I highly encourage you to switch to https://github.com/zeit/pkg
It is rewritten successor of EncloseJS. It is open source, and all improvements will go there.
Please check if pkg has your issue unresolved, and if it is true, reopen your issue there:
https://github.com/zeit/pkg/issues
